### ISSUE TITLE
Not Working with Eclipse Kepler

### ISSUE THREAD

**Issue by jxc876** [Nodeclipse/EditBox#11]
I installed this plugin (v 0.60.0.201405271213) into Eclipse Kepler (SR 2) and also into Eclipse STS 3.6 (Luna 4.4), it doesn't appear to work in either. 

Steps to reproduce:
1) Install plugin from marketplace or from git-hub using link 
2) Restart after installation
3) Verify that plugin is enabled from Preferences
3) Open Java file (or any other file) 
4) No highlighting is present

**Comment by nranvah** [comment]
I tried the same. Installed NodeEclipse Editbox on Kepler SR2.
The plugin is enabled in preferences, and the icon is also selected. The appearance of my JS code hasn't changed one bit.

**Comment by paulvi** [comment]
@nranvah create new issue, and/or ask on stackoverflow.com
