### ISSUE TITLE
Not working with Eclipse Oxygen

### ISSUE THREAD

**Issue by gustavklopp** [Nodeclipse/EditBox#15]
I've installed it from the marketplace.
I've checked in Windows>Preferences>EditBox: It's noted: Enabled.
I've pressed the green icon on the toolbar
restarted Eclipse again. 

I've tested with a Java, and a python file.

**Comment by paulvi** [comment]
There were API changes for base Editor in Eclipse recently. Possibly that causes issues with EditBox
