### ISSUE TITLE
Wrong scoping

### ISSUE THREAD

**Issue by mschwehl** [Nodeclipse/EditBox#9]
when you look at the screenshot on
http://marketplace.eclipse.org/sites/default/files/eb0.png
![](https://marketplace.eclipse.org/sites/default/files/eb0.png)
there should be new (and different) colors for the scopes containing

gradle = a;
gradle = b;

because the code inside if and else have different scopes

**Comment by paulvi** [comment]
It is actually not bug, just default theme defines only 3 levels for color change
